In [1]:
import pandas as pd
import datetime as dt

from sqlalchemy import create_engine

In [2]:
# establish connection to db

rds_connection_string = "postgres:password123@localhost:5432/wow_db"
engine = create_engine(f'postgresql://{rds_connection_string}')

In [3]:
file_loc_coords = "location_coords.csv"

# needed to use "ISO-8859-1" becuse utf-8 encoding did not work for certain special characters
loc_coords_df = pd.read_csv(file_loc_coords, encoding = "ISO-8859-1")

In [4]:
loc_coords_df.head()

,Location_Name,Map_ID,X_coord,Y_coord,Z_coord
0,Eastern Kingdom: Ironforge Airport,0.0,-4488.993311,-1580.19104,509.005066
1,Eastern Kingdom: Wetlands Mountain Camp,0.0,-3855.000000,-3479.00000,579.000000
2,Eastern Kingdom: Dun Morogh plane camp,0.0,-6161.000000,-786.00000,423.000000
3,Eastern Kingdom: Undercity,0.0,1831.260000,238.53000,60.520000
4,Eastern Kingdom: Stormwind City,0.0,-8913.230000,554.63300,93.794400

In [5]:
# Map the lowering function to all column names
loc_coords_df.columns = map(str.lower, loc_coords_df.columns)

In [6]:
loc_coords_df.head()

,location_name,map_id,x_coord,y_coord,z_coord
0,Eastern Kingdom: Ironforge Airport,0.0,-4488.993311,-1580.19104,509.005066
1,Eastern Kingdom: Wetlands Mountain Camp,0.0,-3855.000000,-3479.00000,579.000000
2,Eastern Kingdom: Dun Morogh plane camp,0.0,-6161.000000,-786.00000,423.000000
3,Eastern Kingdom: Undercity,0.0,1831.260000,238.53000,60.520000
4,Eastern Kingdom: Stormwind City,0.0,-8913.230000,554.63300,93.794400

In [7]:
loc_coords_df.to_sql(name='wow_loc_coords', con=engine, if_exists='append', index=False, chunksize=25000, method=None)

In [8]:
file_loc = "locations.csv"

In [9]:
loc_df = pd.read_csv(file_loc)

In [10]:
loc_df.head()

   Map_ID Location_Type     Location_Name Game_Version
0       0     Continent  Eastern Kingdoms          WoW
1       1     Continent          Kalimdor          WoW
2     530     Continent          Outlands          TBC
3     571     Continent         Northrend          WLK
4     646     Continent          Deepholm          CAT

In [11]:
# Map the lowering function to all column names
loc_df.columns = map(str.lower, loc_df.columns)

In [12]:
loc_df.to_sql(name='wow_loc', con=engine, if_exists='append', index=False, chunksize=25000, method=None)

In [13]:
zones_file = "zones.csv"

In [14]:
zones_df = pd.read_csv(zones_file, encoding = "ISO-8859-1")

In [15]:
zones_df.head()

,Zone_Name,Continent,Area,Zone,Subzone,Type,Size,Controlled,Min_req_level,Min_rec_level,Max_rec_level,Min_bot_level,Max_bot_level
0,Durotar,Kalimdor,Central Kalimdor,Durotar,NaN,Zone,NaN,Horde,1,1.0,10.0,1.0,10.0
1,The Barrens,Kalimdor,Central Kalimdor,The Barrens,NaN,Zone,NaN,Contested,1,10.0,35.0,10.0,35.0
2,Silverpine Forest,Eastern Kingdoms,Lordaeron,Silverpine Forest,NaN,Zone,NaN,Horde,1,10.0,20.0,10.0,20.0
3,Stonetalon Mountains,Kalimdor,Central Kalimdor,Stonetalon Mountains,NaN,Zone,NaN,Contested,1,25.0,30.0,25.0,30.0
4,Thunder Bluff,Kalimdor,Central Kalimdor,Thunder Bluff,NaN,City,NaN,Horde,1,1.0,100.0,1.0,100.0

In [16]:
# Map the lowering function to all column names
zones_df.columns = map(str.lower, zones_df.columns)

In [17]:
zones_df.head()

,zone_name,continent,area,zone,subzone,type,size,controlled,min_req_level,min_rec_level,max_rec_level,min_bot_level,max_bot_level
0,Durotar,Kalimdor,Central Kalimdor,Durotar,NaN,Zone,NaN,Horde,1,1.0,10.0,1.0,10.0
1,The Barrens,Kalimdor,Central Kalimdor,The Barrens,NaN,Zone,NaN,Contested,1,10.0,35.0,10.0,35.0
2,Silverpine Forest,Eastern Kingdoms,Lordaeron,Silverpine Forest,NaN,Zone,NaN,Horde,1,10.0,20.0,10.0,20.0
3,Stonetalon Mountains,Kalimdor,Central Kalimdor,Stonetalon Mountains,NaN,Zone,NaN,Contested,1,25.0,30.0,25.0,30.0
4,Thunder Bluff,Kalimdor,Central Kalimdor,Thunder Bluff,NaN,City,NaN,Horde,1,1.0,100.0,1.0,100.0

In [18]:
zones_df['zone_name'].equals(zones_df['zone'])

False

In [19]:
# check to see if the 'zone_name' column is just the same as the 'zone' column
zones_df.loc[~(zones_df['zone_name'] == zones_df['zone'])]

,zone_name,continent,area,zone,subzone,type,size,controlled,min_req_level,min_rec_level,max_rec_level,min_bot_level,max_bot_level
6,Orgrimmar,Kalimdor,Central Kalimdor,Durotar,Orgrimmar,City,NaN,Horde,1,1.0,100.0,1.0,100.0
7,Undercity,Eastern Kingdoms,Lordaeron,Tirisfal Glades,Undercity,City,NaN,Horde,1,1.0,100.0,1.0,100.0
10,Wailing Caverns,Kalimdor,Central Kalimdor,The Barrens,Lushwater Oasis,Dungeon,5.0,Horde,10,15.0,25.0,15.0,20.0
12,Maraudon,Kalimdor,Central Kalimdor,Desolace,Maraudon,Dungeon,5.0,Contested,25,32.0,44.0,36.0,39.0
16,The Temple of Atal'Hakkar,Eastern Kingdoms,Azeroth,Swamp of Sorrows,Sunken Temple,Dungeon,5.0,Contested,45,50.0,60.0,40.0,55.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
155,Vault of Archavon,Northrend,Northrend,Wintergrasp,Wintergrasp Fortress,Dungeon,25.0,Contested,80,80.0,80.0,80.0,80.0
156,The Eye of Eternity,Northrend,Northrend,Borean Tundra,Coldarra,Dungeon,25.0,Contested,80,80.0,80.0,80.0,80.0
157,The Obsidian Sanctum,Northrend,Northrend,Dragonblight,Chamber of Aspects,Dungeon,25.0,Contested,80,80.0,80.0,80.0,80.0
158,<U+9F8D><U+9AA8><U+8352><U+91CE>,Northrend,Northrend,Dragonblight,Dragonblight,Zone,NaN,Contested,1,72.0,75.0,72.0,75.0
159,<U+5317><U+65B9><U+6D77><U+5CB8>,Eastern Kingdoms,Lordaeron,Tirisfal Glades,North Coast,Zone,NaN,Contested,1,1.0,100.0,1.0,100.0

In [20]:
# drop the last two rows with broken zone_name(s)

zones_df.drop(zones_df.tail(2).index,inplace=True)

In [21]:
zones_df.tail()

,zone_name,continent,area,zone,subzone,type,size,controlled,min_req_level,min_rec_level,max_rec_level,min_bot_level,max_bot_level
153,Halls of Stone,Northrend,Northrend,Storm Peaks,Ulduar,Dungeon,5.0,Contested,74,77.0,79.0,77.0,79.0
154,Utgarde Pinnacle,Northrend,Northrend,Utgarde Keep,NaN,Dungeon,5.0,Contested,75,80.0,80.0,80.0,80.0
155,Vault of Archavon,Northrend,Northrend,Wintergrasp,Wintergrasp Fortress,Dungeon,25.0,Contested,80,80.0,80.0,80.0,80.0
156,The Eye of Eternity,Northrend,Northrend,Borean Tundra,Coldarra,Dungeon,25.0,Contested,80,80.0,80.0,80.0,80.0
157,The Obsidian Sanctum,Northrend,Northrend,Dragonblight,Chamber of Aspects,Dungeon,25.0,Contested,80,80.0,80.0,80.0,80.0

In [22]:
zones_df.to_sql(name='wow_zones', con=engine, if_exists='append', index=False, chunksize=25000, method=None)